package com.blueteam.wineshop.service;

import com.blueteam.entity.po.Log;

/**
 * 日志Service
 *
 * @author libra
 */
public interface LogService {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Log
     *
     * @mbg.generated Fri Mar 10 12:39:21 CST 2017
     */
    int insert(Log record);
}
