package com.blueteam.wineshop.mapper;

import com.blueteam.entity.dto.CarriersSearch;
import com.blueteam.entity.dto.CarriersStatistics;
import com.blueteam.entity.po.CarriersInfo;
import com.blueteam.entity.dto.PageResult;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CarriersInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CarriersInfo
     *
     * @mbg.generated Wed Feb 22 10:13:12 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CarriersInfo
     *
     * @mbg.generated Wed Feb 22 10:13:12 CST 2017
     */
    int insert(CarriersInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CarriersInfo
     *
     * @mbg.generated Wed Feb 22 10:13:12 CST 2017
     */
    CarriersInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CarriersInfo
     *
     * @mbg.generated Wed Feb 22 10:13:12 CST 2017
     */
    List<CarriersInfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CarriersInfo
     *
     * @mbg.generated Wed Feb 22 10:13:12 CST 2017
     */
    int updateByPrimaryKey(CarriersInfo record);

    /**
     * 根据用户ID 查询运营商信息
     *
     * @param userId 用户ID
     * @return
     */
    CarriersInfo selectForUser(int userId);

    /**
     * 获取运营商统计信息
     *
     * @param carriersId 运营商ID
     * @return
     */
    CarriersStatistics getStatistics(int carriersId);

    /**
     * 根据查询条件分页查询运营商
     *
     * @param search
     * @return
     */
    PageResult<List<CarriersInfo>> selectCarriersByWhere(CarriersSearch search);

    /**
     * 获取指定管理区域的运营商ID
     *
     * @param cityCode
     * @return
     */
    Integer selectByManagerArea(String cityCode);

    /**
     * 方法的功能描述:TODO 根据citycode获取运营商名字
     *
     * @param
     * @return
     * @methodName
     * @author xiaojiang 2017/5/17 15:18
     * @since 1.3.0
     */
    String findManagerArea(String cityCode);

    /**
     * 根据运营商ID获取运营商信息
     *
     * @param id 运营商ID
     * @return
     */
    CarriersInfo getCarriersByID(int id);

    /**
     * 根据运营商CityCode获取运营商信息
     *
     * @param CityCode 运营商CityCode
     * @return
     */
    CarriersInfo getCarriersByCode(String CityCode);

    /**
     * 查看可以管理指定区域的运营商
     *
     * @param cityCode
     * @return
     */
    CarriersInfo selectCarriersByManagerCityCode(@Param("cityCode") String cityCode);
}