package com.blueteam.wineshop.mapper;

import com.blueteam.entity.po.Log;

import java.util.List;

public interface LogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Log
     *
     * @mbg.generated Fri Mar 10 12:39:21 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Log
     *
     * @mbg.generated Fri Mar 10 12:39:21 CST 2017
     */
    int insert(Log record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Log
     *
     * @mbg.generated Fri Mar 10 12:39:21 CST 2017
     */
    Log selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Log
     *
     * @mbg.generated Fri Mar 10 12:39:21 CST 2017
     */
    List<Log> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Log
     *
     * @mbg.generated Fri Mar 10 12:39:21 CST 2017
     */
    int updateByPrimaryKey(Log record);
}