package com.blueteam.entity.po;

import com.blueteam.base.util.DateUtil;

import java.util.Date;

public abstract class BaseModel {
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column OrderInfo.CreateBy
     *
     * @mbg.generated Sat Feb 18 11:02:07 CST 2017
     */
    private String createby;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column OrderInfo.CreateDate
     *
     * @mbg.generated Sat Feb 18 11:02:07 CST 2017
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column OrderInfo.UpdateBy
     *
     * @mbg.generated Sat Feb 18 11:02:07 CST 2017
     */
    private String updateby;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column OrderInfo.UpdateDate
     *
     * @mbg.generated Sat Feb 18 11:02:07 CST 2017
     */
    private Date updatedate;

    public String getCreateby() {
        return createby;
    }

    public void setCreateby(String createby) {
        this.createby = createby;
    }

    public Date getCreatedate() {
        return createdate;
    }

    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    public String getUpdateby() {
        return updateby;
    }

    public void setUpdateby(String updateby) {
        this.updateby = updateby;
    }

    public Date getUpdatedate() {
        return updatedate;
    }

    public void setUpdatedate(Date updatedate) {
        this.updatedate = updatedate;
    }

    /**
     * 获取更新时间 字符串
     *
     * @return
     */
    public String getUpdateStr() {
        return DateUtil.format(getUpdatedate());
    }

    /**
     * 获取创建时间字符串
     *
     * @return
     */
    public String getCreatedateStr() {
        return DateUtil.format(getCreatedate());
    }
}
