package com.blueteam.entity.po;

import com.blueteam.entity.dto.City;

import java.math.BigDecimal;

public class CarriersInfo extends BaseModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CarriersInfo.Id
     *
     * @mbg.generated Wed Feb 22 10:13:12 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CarriersInfo.Name
     *
     * @mbg.generated Wed Feb 22 10:13:12 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CarriersInfo.CityCode
     *
     * @mbg.generated Wed Feb 22 10:13:12 CST 2017
     */
    private String citycode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CarriersInfo.Addr
     *
     * @mbg.generated Wed Feb 22 10:13:12 CST 2017
     */
    private String addr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CarriersInfo.ManagementArea
     *
     * @mbg.generated Wed Feb 22 10:13:12 CST 2017
     */
    private String managementarea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CarriersInfo.Lon
     *
     * @mbg.generated Wed Feb 22 10:13:12 CST 2017
     */
    private BigDecimal lon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CarriersInfo.Lat
     *
     * @mbg.generated Wed Feb 22 10:13:12 CST 2017
     */
    private BigDecimal lat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CarriersInfo.Phone
     *
     * @mbg.generated Wed Feb 22 10:13:12 CST 2017
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CarriersInfo.Status
     *
     * @mbg.generated Wed Feb 22 10:13:12 CST 2017
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CarriersInfo.UserID
     *
     * @mbg.generated Wed Feb 22 10:13:12 CST 2017
     */
    private Integer userid;


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CarriersInfo.Id
     *
     * @return the value of CarriersInfo.Id
     * @mbg.generated Wed Feb 22 10:13:12 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CarriersInfo.Id
     *
     * @param id the value for CarriersInfo.Id
     * @mbg.generated Wed Feb 22 10:13:12 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CarriersInfo.Name
     *
     * @return the value of CarriersInfo.Name
     * @mbg.generated Wed Feb 22 10:13:12 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CarriersInfo.Name
     *
     * @param name the value for CarriersInfo.Name
     * @mbg.generated Wed Feb 22 10:13:12 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CarriersInfo.CityCode
     *
     * @return the value of CarriersInfo.CityCode
     * @mbg.generated Wed Feb 22 10:13:12 CST 2017
     */
    public String getCitycode() {
        return citycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CarriersInfo.CityCode
     *
     * @param citycode the value for CarriersInfo.CityCode
     * @mbg.generated Wed Feb 22 10:13:12 CST 2017
     */
    public void setCitycode(String citycode) {
        this.citycode = citycode == null ? null : citycode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CarriersInfo.Addr
     *
     * @return the value of CarriersInfo.Addr
     * @mbg.generated Wed Feb 22 10:13:12 CST 2017
     */
    public String getAddr() {
        return addr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CarriersInfo.Addr
     *
     * @param addr the value for CarriersInfo.Addr
     * @mbg.generated Wed Feb 22 10:13:12 CST 2017
     */
    public void setAddr(String addr) {
        this.addr = addr == null ? null : addr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CarriersInfo.ManagementArea
     *
     * @return the value of CarriersInfo.ManagementArea
     * @mbg.generated Wed Feb 22 10:13:12 CST 2017
     */
    public String getManagementarea() {
        return managementarea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CarriersInfo.ManagementArea
     *
     * @param managementarea the value for CarriersInfo.ManagementArea
     * @mbg.generated Wed Feb 22 10:13:12 CST 2017
     */
    public void setManagementarea(String managementarea) {
        this.managementarea = managementarea == null ? null : managementarea.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CarriersInfo.Lon
     *
     * @return the value of CarriersInfo.Lon
     * @mbg.generated Wed Feb 22 10:13:12 CST 2017
     */
    public BigDecimal getLon() {
        return lon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CarriersInfo.Lon
     *
     * @param lon the value for CarriersInfo.Lon
     * @mbg.generated Wed Feb 22 10:13:12 CST 2017
     */
    public void setLon(BigDecimal lon) {
        this.lon = lon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CarriersInfo.Lat
     *
     * @return the value of CarriersInfo.Lat
     * @mbg.generated Wed Feb 22 10:13:12 CST 2017
     */
    public BigDecimal getLat() {
        return lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CarriersInfo.Lat
     *
     * @param lat the value for CarriersInfo.Lat
     * @mbg.generated Wed Feb 22 10:13:12 CST 2017
     */
    public void setLat(BigDecimal lat) {
        this.lat = lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CarriersInfo.Phone
     *
     * @return the value of CarriersInfo.Phone
     * @mbg.generated Wed Feb 22 10:13:12 CST 2017
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CarriersInfo.Phone
     *
     * @param phone the value for CarriersInfo.Phone
     * @mbg.generated Wed Feb 22 10:13:12 CST 2017
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CarriersInfo.Status
     *
     * @return the value of CarriersInfo.Status
     * @mbg.generated Wed Feb 22 10:13:12 CST 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CarriersInfo.Status
     *
     * @param status the value for CarriersInfo.Status
     * @mbg.generated Wed Feb 22 10:13:12 CST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CarriersInfo.UserID
     *
     * @return the value of CarriersInfo.UserID
     * @mbg.generated Wed Feb 22 10:13:12 CST 2017
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CarriersInfo.UserID
     *
     * @param userid the value for CarriersInfo.UserID
     * @mbg.generated Wed Feb 22 10:13:12 CST 2017
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * 登录账号
     */
    private String userName;

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    //扩展字段
    /**
     * 城市
     */
    private City city;

    /**
     * 负责人姓名
     */
    private String personName;
    /**
     * 负责人电话
     */
    private String personPhone;

    /**
     * 管理区域名称
     */
    private String managerAreaName;

    public String getPersonName() {
        return personName;
    }

    public void setPersonName(String personName) {
        this.personName = personName;
    }

    public String getPersonPhone() {
        return personPhone;
    }

    public void setPersonPhone(String personPhone) {
        this.personPhone = personPhone;
    }

    public String getManagerAreaName() {
        return managerAreaName;
    }

    public void setManagerAreaName(String managerAreaName) {
        this.managerAreaName = managerAreaName;
    }

    public City getCity() {
        return city;
    }

    public void setCity(City city) {
        this.city = city;
    }
}