package com.blueteam.entity.po;

import java.util.Date;

public class Log {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Log.Id
     *
     * @mbg.generated Fri Mar 10 12:39:21 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Log.TargetMethod
     *
     * @mbg.generated Fri Mar 10 12:39:21 CST 2017
     */
    private String targetmethod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Log.MethodDescription
     *
     * @mbg.generated Fri Mar 10 12:39:21 CST 2017
     */
    private String methoddescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Log.RequestName
     *
     * @mbg.generated Fri Mar 10 12:39:21 CST 2017
     */
    private String requestname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Log.RequestIP
     *
     * @mbg.generated Fri Mar 10 12:39:21 CST 2017
     */
    private String requestip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Log.ExceptionCode
     *
     * @mbg.generated Fri Mar 10 12:39:21 CST 2017
     */
    private String exceptioncode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Log.ExceptionDetail
     *
     * @mbg.generated Fri Mar 10 12:39:21 CST 2017
     */
    private String exceptiondetail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Log.CreateBy
     *
     * @mbg.generated Fri Mar 10 12:39:21 CST 2017
     */
    private String createby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Log.CreateDate
     *
     * @mbg.generated Fri Mar 10 12:39:21 CST 2017
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Log.RequestUrl
     *
     * @mbg.generated Fri Mar 10 12:39:21 CST 2017
     */
    private String requesturl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Log.RequestParamter
     *
     * @mbg.generated Fri Mar 10 12:39:21 CST 2017
     */
    private String requestparamter;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Log.RequestToken
     *
     * @mbg.generated Fri Mar 10 12:39:21 CST 2017
     */
    private String requesttoken;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Log.RequestUserAgent
     *
     * @mbg.generated Fri Mar 10 12:39:21 CST 2017
     */
    private String requestuseragent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Log.Id
     *
     * @return the value of Log.Id
     * @mbg.generated Fri Mar 10 12:39:21 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Log.Id
     *
     * @param id the value for Log.Id
     * @mbg.generated Fri Mar 10 12:39:21 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Log.TargetMethod
     *
     * @return the value of Log.TargetMethod
     * @mbg.generated Fri Mar 10 12:39:21 CST 2017
     */
    public String getTargetmethod() {
        return targetmethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Log.TargetMethod
     *
     * @param targetmethod the value for Log.TargetMethod
     * @mbg.generated Fri Mar 10 12:39:21 CST 2017
     */
    public void setTargetmethod(String targetmethod) {
        this.targetmethod = targetmethod == null ? null : targetmethod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Log.MethodDescription
     *
     * @return the value of Log.MethodDescription
     * @mbg.generated Fri Mar 10 12:39:21 CST 2017
     */
    public String getMethoddescription() {
        return methoddescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Log.MethodDescription
     *
     * @param methoddescription the value for Log.MethodDescription
     * @mbg.generated Fri Mar 10 12:39:21 CST 2017
     */
    public void setMethoddescription(String methoddescription) {
        this.methoddescription = methoddescription == null ? null : methoddescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Log.RequestName
     *
     * @return the value of Log.RequestName
     * @mbg.generated Fri Mar 10 12:39:21 CST 2017
     */
    public String getRequestname() {
        return requestname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Log.RequestName
     *
     * @param requestname the value for Log.RequestName
     * @mbg.generated Fri Mar 10 12:39:21 CST 2017
     */
    public void setRequestname(String requestname) {
        this.requestname = requestname == null ? null : requestname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Log.RequestIP
     *
     * @return the value of Log.RequestIP
     * @mbg.generated Fri Mar 10 12:39:21 CST 2017
     */
    public String getRequestip() {
        return requestip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Log.RequestIP
     *
     * @param requestip the value for Log.RequestIP
     * @mbg.generated Fri Mar 10 12:39:21 CST 2017
     */
    public void setRequestip(String requestip) {
        this.requestip = requestip == null ? null : requestip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Log.ExceptionCode
     *
     * @return the value of Log.ExceptionCode
     * @mbg.generated Fri Mar 10 12:39:21 CST 2017
     */
    public String getExceptioncode() {
        return exceptioncode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Log.ExceptionCode
     *
     * @param exceptioncode the value for Log.ExceptionCode
     * @mbg.generated Fri Mar 10 12:39:21 CST 2017
     */
    public void setExceptioncode(String exceptioncode) {
        this.exceptioncode = exceptioncode == null ? null : exceptioncode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Log.ExceptionDetail
     *
     * @return the value of Log.ExceptionDetail
     * @mbg.generated Fri Mar 10 12:39:21 CST 2017
     */
    public String getExceptiondetail() {
        return exceptiondetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Log.ExceptionDetail
     *
     * @param exceptiondetail the value for Log.ExceptionDetail
     * @mbg.generated Fri Mar 10 12:39:21 CST 2017
     */
    public void setExceptiondetail(String exceptiondetail) {
        this.exceptiondetail = exceptiondetail == null ? null : exceptiondetail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Log.CreateBy
     *
     * @return the value of Log.CreateBy
     * @mbg.generated Fri Mar 10 12:39:21 CST 2017
     */
    public String getCreateby() {
        return createby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Log.CreateBy
     *
     * @param createby the value for Log.CreateBy
     * @mbg.generated Fri Mar 10 12:39:21 CST 2017
     */
    public void setCreateby(String createby) {
        this.createby = createby == null ? null : createby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Log.CreateDate
     *
     * @return the value of Log.CreateDate
     * @mbg.generated Fri Mar 10 12:39:21 CST 2017
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Log.CreateDate
     *
     * @param createdate the value for Log.CreateDate
     * @mbg.generated Fri Mar 10 12:39:21 CST 2017
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Log.RequestUrl
     *
     * @return the value of Log.RequestUrl
     * @mbg.generated Fri Mar 10 12:39:21 CST 2017
     */
    public String getRequesturl() {
        return requesturl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Log.RequestUrl
     *
     * @param requesturl the value for Log.RequestUrl
     * @mbg.generated Fri Mar 10 12:39:21 CST 2017
     */
    public void setRequesturl(String requesturl) {
        this.requesturl = requesturl == null ? null : requesturl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Log.RequestParamter
     *
     * @return the value of Log.RequestParamter
     * @mbg.generated Fri Mar 10 12:39:21 CST 2017
     */
    public String getRequestparamter() {
        return requestparamter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Log.RequestParamter
     *
     * @param requestparamter the value for Log.RequestParamter
     * @mbg.generated Fri Mar 10 12:39:21 CST 2017
     */
    public void setRequestparamter(String requestparamter) {
        this.requestparamter = requestparamter == null ? null : requestparamter.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Log.RequestToken
     *
     * @return the value of Log.RequestToken
     * @mbg.generated Fri Mar 10 12:39:21 CST 2017
     */
    public String getRequesttoken() {
        return requesttoken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Log.RequestToken
     *
     * @param requesttoken the value for Log.RequestToken
     * @mbg.generated Fri Mar 10 12:39:21 CST 2017
     */
    public void setRequesttoken(String requesttoken) {
        this.requesttoken = requesttoken == null ? null : requesttoken.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Log.RequestUserAgent
     *
     * @return the value of Log.RequestUserAgent
     * @mbg.generated Fri Mar 10 12:39:21 CST 2017
     */
    public String getRequestuseragent() {
        return requestuseragent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Log.RequestUserAgent
     *
     * @param requestuseragent the value for Log.RequestUserAgent
     * @mbg.generated Fri Mar 10 12:39:21 CST 2017
     */
    public void setRequestuseragent(String requestuseragent) {
        this.requestuseragent = requestuseragent == null ? null : requestuseragent.trim();
    }
}