package com.blueteam.entity.po;

import com.blueteam.entity.dto.City;

import java.math.BigDecimal;
import java.util.Date;

/**
 * @author Marx
 * <p>
 * Orderinfo.java
 * <p>
 * 2017年2月22日**@version 1.0
 */
public class OrderInfo extends BaseModel {
    /**
     * 待付款
     */
    public static final int ORDER_STATUS_WAITING_PAY = 10;
    /**
     * 已付款
     */
    public static final int ORDER_STATUS_FINISH_PAY = 20;
    /**
     * 已完成
     */
    public static final int ORDER_STATUS_FINISH_FINISHED = 30;
    /**
     * 已关闭(其它原因关闭订单)
     */
    public static final int ORDER_STATUS_SHUT_DOWN = 40;
    /**
     * 已退款
     */
    public static final int ORDER_STATUS_ERROR = 90;
    private String StateName;
    /**
     * version:数据版本号.
     */
    private int version;

    public int getVersion() {
        return version;
    }

    public void setVersion(int version) {
        this.version = version;
    }

    public String getStateName() {
        return StateName;
    }

    public void setStateName(String stateName) {
        StateName = stateName;
    }

    private VendorInfo vendorInfo;

    public VendorInfo getVendorInfo() {
        return vendorInfo;
    }

    public void setVendorInfo(VendorInfo vendorInfo) {
        this.vendorInfo = vendorInfo;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OrderInfo.Id
     *
     * @mbg.generated Sat Feb 18 11:02:07 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OrderInfo.OrderNo
     *
     * @mbg.generated Sat Feb 18 11:02:07 CST 2017
     */
    private String orderno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OrderInfo.VendorId
     *
     * @mbg.generated Sat Feb 18 11:02:07 CST 2017
     */
    private Integer vendorid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OrderInfo.Title
     *
     * @mbg.generated Sat Feb 18 11:02:07 CST 2017
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OrderInfo.UserId
     *
     * @mbg.generated Sat Feb 18 11:02:07 CST 2017
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OrderInfo.BookTime
     *
     * @mbg.generated Sat Feb 18 11:02:07 CST 2017
     */
    private Date booktime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OrderInfo.Remark
     *
     * @mbg.generated Sat Feb 18 11:02:07 CST 2017
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OrderInfo.ProductId
     *
     * @mbg.generated Sat Feb 18 11:02:07 CST 2017
     */
    private Integer productid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OrderInfo.Price
     *
     * @mbg.generated Sat Feb 18 11:02:07 CST 2017
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OrderInfo.Count
     *
     * @mbg.generated Sat Feb 18 11:02:07 CST 2017
     */
    private Integer count;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OrderInfo.TotalMoney
     *
     * @mbg.generated Sat Feb 18 11:02:07 CST 2017
     */
    private BigDecimal totalmoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OrderInfo.PayWay
     *
     * @mbg.generated Sat Feb 18 11:02:07 CST 2017
     */
    private String payway;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OrderInfo.PayTime
     *
     * @mbg.generated Sat Feb 18 11:02:07 CST 2017
     */
    private Date paytime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OrderInfo.PayCode
     *
     * @mbg.generated Sat Feb 18 11:02:07 CST 2017
     */
    private String paycode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OrderInfo.OrderStatus
     *
     * @mbg.generated Sat Feb 18 11:02:07 CST 2017
     */
    private Integer orderstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OrderInfo.FinishTime
     *
     * @mbg.generated Sat Feb 18 11:02:07 CST 2017
     */
    private Date finishtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OrderInfo.RefundTime
     *
     * @mbg.generated Sat Feb 18 11:02:07 CST 2017
     */
    private Date refundtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OrderInfo.CouponId
     *
     * @mbg.generated Sat Feb 18 11:02:07 CST 2017
     */
    private Integer couponid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OrderInfo.RefundMoney
     *
     * @mbg.generated Sat Feb 18 11:02:07 CST 2017
     */
    private BigDecimal refundmoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OrderInfo.DiscountAmount
     *
     * @mbg.generated Sat Feb 18 11:02:07 CST 2017
     */
    private BigDecimal discountamount;
    private BigDecimal settlement_money;


    /**
     * 扩展，支付用户名称
     */
    private String nickName;


    public String getNickName() {
        return nickName;
    }

    public void setNickName(String nickName) {
        this.nickName = nickName;
    }

    /**
     * 结算金额
     *
     * @return
     */
    public BigDecimal getSettlement_money() {
        return settlement_money;
    }

    /**
     * 结算金额
     *
     * @return
     */
    public void setSettlement_money(BigDecimal settlement_money) {
        this.settlement_money = settlement_money;
    }

    private String tradingArea;

    public String getTradingArea() {
        return tradingArea;
    }

    public void setTradingArea(String tradingArea) {
        this.tradingArea = tradingArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OrderInfo.Id
     *
     * @return the value of OrderInfo.Id
     * @mbg.generated Sat Feb 18 11:02:07 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OrderInfo.Id
     *
     * @param id the value for OrderInfo.Id
     * @mbg.generated Sat Feb 18 11:02:07 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OrderInfo.OrderNo
     *
     * @return the value of OrderInfo.OrderNo
     * @mbg.generated Sat Feb 18 11:02:07 CST 2017
     */
    public String getOrderno() {
        return orderno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OrderInfo.OrderNo
     *
     * @param orderno the value for OrderInfo.OrderNo
     * @mbg.generated Sat Feb 18 11:02:07 CST 2017
     */
    public void setOrderno(String orderno) {
        this.orderno = orderno == null ? null : orderno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OrderInfo.VendorId
     *
     * @return the value of OrderInfo.VendorId
     * @mbg.generated Sat Feb 18 11:02:07 CST 2017
     */
    public Integer getVendorid() {
        return vendorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OrderInfo.VendorId
     *
     * @param vendorid the value for OrderInfo.VendorId
     * @mbg.generated Sat Feb 18 11:02:07 CST 2017
     */
    public void setVendorid(Integer vendorid) {
        this.vendorid = vendorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OrderInfo.Title
     *
     * @return the value of OrderInfo.Title
     * @mbg.generated Sat Feb 18 11:02:07 CST 2017
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OrderInfo.Title
     *
     * @param title the value for OrderInfo.Title
     * @mbg.generated Sat Feb 18 11:02:07 CST 2017
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OrderInfo.UserId
     *
     * @return the value of OrderInfo.UserId
     * @mbg.generated Sat Feb 18 11:02:07 CST 2017
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OrderInfo.UserId
     *
     * @param userid the value for OrderInfo.UserId
     * @mbg.generated Sat Feb 18 11:02:07 CST 2017
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OrderInfo.BookTime
     *
     * @return the value of OrderInfo.BookTime
     * @mbg.generated Sat Feb 18 11:02:07 CST 2017
     */
    public Date getBooktime() {
        return booktime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OrderInfo.BookTime
     *
     * @param booktime the value for OrderInfo.BookTime
     * @mbg.generated Sat Feb 18 11:02:07 CST 2017
     */
    public void setBooktime(Date booktime) {
        this.booktime = booktime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OrderInfo.Remark
     *
     * @return the value of OrderInfo.Remark
     * @mbg.generated Sat Feb 18 11:02:07 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OrderInfo.Remark
     *
     * @param remark the value for OrderInfo.Remark
     * @mbg.generated Sat Feb 18 11:02:07 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OrderInfo.ProductId
     *
     * @return the value of OrderInfo.ProductId
     * @mbg.generated Sat Feb 18 11:02:07 CST 2017
     */
    public Integer getProductid() {
        return productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OrderInfo.ProductId
     *
     * @param productid the value for OrderInfo.ProductId
     * @mbg.generated Sat Feb 18 11:02:07 CST 2017
     */
    public void setProductid(Integer productid) {
        this.productid = productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OrderInfo.Price
     *
     * @return the value of OrderInfo.Price
     * @mbg.generated Sat Feb 18 11:02:07 CST 2017
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OrderInfo.Price
     *
     * @param price the value for OrderInfo.Price
     * @mbg.generated Sat Feb 18 11:02:07 CST 2017
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OrderInfo.Count
     *
     * @return the value of OrderInfo.Count
     * @mbg.generated Sat Feb 18 11:02:07 CST 2017
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OrderInfo.Count
     *
     * @param count the value for OrderInfo.Count
     * @mbg.generated Sat Feb 18 11:02:07 CST 2017
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OrderInfo.TotalMoney
     *
     * @return the value of OrderInfo.TotalMoney
     * @mbg.generated Sat Feb 18 11:02:07 CST 2017
     */
    public BigDecimal getTotalmoney() {
        return totalmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OrderInfo.TotalMoney
     *
     * @param totalmoney the value for OrderInfo.TotalMoney
     * @mbg.generated Sat Feb 18 11:02:07 CST 2017
     */
    public void setTotalmoney(BigDecimal totalmoney) {
        this.totalmoney = totalmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OrderInfo.PayWay
     *
     * @return the value of OrderInfo.PayWay
     * @mbg.generated Sat Feb 18 11:02:07 CST 2017
     */
    public String getPayway() {
        return payway;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OrderInfo.PayWay
     *
     * @param payway the value for OrderInfo.PayWay
     * @mbg.generated Sat Feb 18 11:02:07 CST 2017
     */
    public void setPayway(String payway) {
        this.payway = payway == null ? null : payway.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OrderInfo.PayTime
     *
     * @return the value of OrderInfo.PayTime
     * @mbg.generated Sat Feb 18 11:02:07 CST 2017
     */
    public Date getPaytime() {
        return paytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OrderInfo.PayTime
     *
     * @param paytime the value for OrderInfo.PayTime
     * @mbg.generated Sat Feb 18 11:02:07 CST 2017
     */
    public void setPaytime(Date paytime) {
        this.paytime = paytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OrderInfo.PayCode
     *
     * @return the value of OrderInfo.PayCode
     * @mbg.generated Sat Feb 18 11:02:07 CST 2017
     */
    public String getPaycode() {
        return paycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OrderInfo.PayCode
     *
     * @param paycode the value for OrderInfo.PayCode
     * @mbg.generated Sat Feb 18 11:02:07 CST 2017
     */
    public void setPaycode(String paycode) {
        this.paycode = paycode == null ? null : paycode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OrderInfo.OrderStatus
     *
     * @return the value of OrderInfo.OrderStatus
     * @mbg.generated Sat Feb 18 11:02:07 CST 2017
     */
    public Integer getOrderstatus() {
        return orderstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OrderInfo.OrderStatus
     *
     * @param orderstatus the value for OrderInfo.OrderStatus
     * @mbg.generated Sat Feb 18 11:02:07 CST 2017
     */
    public void setOrderstatus(Integer orderstatus) {
        this.orderstatus = orderstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OrderInfo.FinishTime
     *
     * @return the value of OrderInfo.FinishTime
     * @mbg.generated Sat Feb 18 11:02:07 CST 2017
     */
    public Date getFinishtime() {
        return finishtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OrderInfo.FinishTime
     *
     * @param finishtime the value for OrderInfo.FinishTime
     * @mbg.generated Sat Feb 18 11:02:07 CST 2017
     */
    public void setFinishtime(Date finishtime) {
        this.finishtime = finishtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OrderInfo.RefundTime
     *
     * @return the value of OrderInfo.RefundTime
     * @mbg.generated Sat Feb 18 11:02:07 CST 2017
     */
    public Date getRefundtime() {
        return refundtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OrderInfo.RefundTime
     *
     * @param refundtime the value for OrderInfo.RefundTime
     * @mbg.generated Sat Feb 18 11:02:07 CST 2017
     */
    public void setRefundtime(Date refundtime) {
        this.refundtime = refundtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OrderInfo.CouponId
     *
     * @return the value of OrderInfo.CouponId
     * @mbg.generated Sat Feb 18 11:02:07 CST 2017
     */
    public Integer getCouponid() {
        return couponid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OrderInfo.CouponId
     *
     * @param couponid the value for OrderInfo.CouponId
     * @mbg.generated Sat Feb 18 11:02:07 CST 2017
     */
    public void setCouponid(Integer couponid) {
        this.couponid = couponid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OrderInfo.RefundMoney
     *
     * @return the value of OrderInfo.RefundMoney
     * @mbg.generated Sat Feb 18 11:02:07 CST 2017
     */
    public BigDecimal getRefundmoney() {
        return refundmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OrderInfo.RefundMoney
     *
     * @param refundmoney the value for OrderInfo.RefundMoney
     * @mbg.generated Sat Feb 18 11:02:07 CST 2017
     */
    public void setRefundmoney(BigDecimal refundmoney) {
        this.refundmoney = refundmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OrderInfo.DiscountAmount
     *
     * @return the value of OrderInfo.DiscountAmount
     * @mbg.generated Sat Feb 18 11:02:07 CST 2017
     */
    public BigDecimal getDiscountamount() {
        return discountamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OrderInfo.DiscountAmount
     *
     * @param discountamount the value for OrderInfo.DiscountAmount
     * @mbg.generated Sat Feb 18 11:02:07 CST 2017
     */
    public void setDiscountamount(BigDecimal discountamount) {
        this.discountamount = discountamount;
    }

    /***
     * 日期处理
     *
     */
    private String payTimeStr;

    public String getPayTimeStr() {
        return payTimeStr;
    }

    public void setPayTimeStr(String payTimeStr) {
        this.payTimeStr = payTimeStr;
    }


    /**
     * 消费城市
     */
    private City city;

    /**
     * 商家名称
     */
    private String vendorName;

    public City getCity() {
        return city;
    }

    public void setCity(City city) {
        this.city = city;
    }

    public String getVendorName() {
        return vendorName;
    }

    public void setVendorName(String vendorName) {
        this.vendorName = vendorName;
    }

    public String getVendorImage() {
        return vendorImage;
    }

    public void setVendorImage(String vendorImage) {
        this.vendorImage = vendorImage;
    }

    /**
     * 商家头像
     */
    private String vendorImage;
}