package com.blueteam.entity.po;

import com.blueteam.base.constant.Enums;
import com.blueteam.entity.dto.City;

import java.util.Date;
import java.util.List;

/**
 * @author Marx
 * <p>
 * UserInfo.java
 * <p>
 * 2017年2月22日**@version 1.0
 */
public class UserInfo extends BaseModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UserInfo.Id
     *
     * @mbg.generated Mon Feb 20 11:11:38 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UserInfo.UserName
     *
     * @mbg.generated Mon Feb 20 11:11:38 CST 2017
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UserInfo.NickName
     *
     * @mbg.generated Mon Feb 20 11:11:38 CST 2017
     */
    private String nickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UserInfo.UserTypes
     *
     * @mbg.generated Mon Feb 20 11:11:38 CST 2017
     */
    private int usertypes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UserInfo.AuditStatus
     *
     * @mbg.generated Mon Feb 20 11:11:38 CST 2017
     */
    private Integer auditstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UserInfo.IsLock
     *
     * @mbg.generated Mon Feb 20 11:11:38 CST 2017
     */
    private Enums.EnumUserIsLock islock;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UserInfo.Email
     *
     * @mbg.generated Mon Feb 20 11:11:38 CST 2017
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UserInfo.Telephone
     *
     * @mbg.generated Mon Feb 20 11:11:38 CST 2017
     */
    private String telephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UserInfo.RegisterIp
     *
     * @mbg.generated Mon Feb 20 11:11:38 CST 2017
     */
    private String registerip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UserInfo.LoginTime
     *
     * @mbg.generated Mon Feb 20 11:11:38 CST 2017
     */
    private Date logintime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UserInfo.Remark
     *
     * @mbg.generated Mon Feb 20 11:11:38 CST 2017
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UserInfo.DataSource
     *
     * @mbg.generated Mon Feb 20 11:11:38 CST 2017
     */
    private String datasource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UserInfo.HeadImage
     *
     * @mbg.generated Mon Feb 20 11:11:38 CST 2017
     */
    private String headimage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UserInfo.CityCode
     *
     * @mbg.generated Mon Feb 20 11:11:38 CST 2017
     */
    private String citycode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column UserInfo.WxOpenId
     *
     * @mbg.generated Mon Feb 20 11:11:38 CST 2017
     */
    private String wxopenid;


    /**
     * 地址
     */
    private String addr;


    /**
     * 用户积分扩展字段（C端专用）
     *
     * @return
     */
    private String jifen;


    /**
     * 用户密码
     */
    private String userPwd;

    /**
     * 密码掩码
     */
    private String passwordSalt;

    /**
     * 设备号
     * <p>
     * 前缀为 Device 名称+：+设备号
     */
    private String device_tokens;

    /**
     * 用户绑定的商家微信公众号的openid
     */
    private String vendorWxOpenId;

    private List<ThirdPartyUserInfo> thirdPartyUserInfos;

    public List<ThirdPartyUserInfo> getThirdPartyUserInfos() {
        return thirdPartyUserInfos;
    }

    public void setThirdPartyUserInfos(List<ThirdPartyUserInfo> thirdPartyUserInfos) {
        this.thirdPartyUserInfos = thirdPartyUserInfos;
    }

    public String getVendorWxOpenId() {
        return vendorWxOpenId;
    }

    public void setVendorWxOpenId(String vendorWxOpenId) {
        this.vendorWxOpenId = vendorWxOpenId;
    }

    public String getDevice_tokens() {
        return device_tokens;
    }

    public void setDevice_tokens(String device_tokens) {
        this.device_tokens = device_tokens;
    }

    public String getUserPwd() {
        return userPwd;
    }

    public void setUserPwd(String userPwd) {
        this.userPwd = userPwd;
    }

    public String getPasswordSalt() {
        return passwordSalt;
    }

    public void setPasswordSalt(String passwordSalt) {
        this.passwordSalt = passwordSalt;
    }

    public String getJifen() {
        return jifen;
    }

    public void setJifen(String jifen) {
        this.jifen = jifen;
    }

    public String getAddr() {
        return addr;
    }

    public void setAddr(String addr) {
        this.addr = addr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UserInfo.Id
     *
     * @return the value of UserInfo.Id
     * @mbg.generated Mon Feb 20 11:11:38 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UserInfo.Id
     *
     * @param id the value for UserInfo.Id
     * @mbg.generated Mon Feb 20 11:11:38 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UserInfo.UserName
     *
     * @return the value of UserInfo.UserName
     * @mbg.generated Mon Feb 20 11:11:38 CST 2017
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UserInfo.UserName
     *
     * @param username the value for UserInfo.UserName
     * @mbg.generated Mon Feb 20 11:11:38 CST 2017
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UserInfo.NickName
     *
     * @return the value of UserInfo.NickName
     * @mbg.generated Mon Feb 20 11:11:38 CST 2017
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UserInfo.NickName
     *
     * @param nickname the value for UserInfo.NickName
     * @mbg.generated Mon Feb 20 11:11:38 CST 2017
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UserInfo.UserTypes
     *
     * @return the value of UserInfo.UserTypes
     * @mbg.generated Mon Feb 20 11:11:38 CST 2017
     */
    public int getUsertypes() {
        return usertypes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UserInfo.UserTypes
     *
     * @param usertypes the value for UserInfo.UserTypes
     * @mbg.generated Mon Feb 20 11:11:38 CST 2017
     */
    public void setUsertypes(int usertypes) {
        this.usertypes = usertypes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UserInfo.AuditStatus
     *
     * @return the value of UserInfo.AuditStatus
     * @mbg.generated Mon Feb 20 11:11:38 CST 2017
     */
    public Integer getAuditstatus() {
        return auditstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UserInfo.AuditStatus
     *
     * @param auditstatus the value for UserInfo.AuditStatus
     * @mbg.generated Mon Feb 20 11:11:38 CST 2017
     */
    public void setAuditstatus(Integer auditstatus) {
        this.auditstatus = auditstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UserInfo.IsLock
     *
     * @return the value of UserInfo.IsLock
     * @mbg.generated Mon Feb 20 11:11:38 CST 2017
     */
    public Enums.EnumUserIsLock getIslock() {
        return islock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UserInfo.IsLock
     *
     * @param islock the value for UserInfo.IsLock
     * @mbg.generated Mon Feb 20 11:11:38 CST 2017
     */
    public void setIslock(Enums.EnumUserIsLock islock) {
        this.islock = islock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UserInfo.Email
     *
     * @return the value of UserInfo.Email
     * @mbg.generated Mon Feb 20 11:11:38 CST 2017
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UserInfo.Email
     *
     * @param email the value for UserInfo.Email
     * @mbg.generated Mon Feb 20 11:11:38 CST 2017
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UserInfo.Telephone
     *
     * @return the value of UserInfo.Telephone
     * @mbg.generated Mon Feb 20 11:11:38 CST 2017
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UserInfo.Telephone
     *
     * @param telephone the value for UserInfo.Telephone
     * @mbg.generated Mon Feb 20 11:11:38 CST 2017
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UserInfo.RegisterIp
     *
     * @return the value of UserInfo.RegisterIp
     * @mbg.generated Mon Feb 20 11:11:38 CST 2017
     */
    public String getRegisterip() {
        return registerip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UserInfo.RegisterIp
     *
     * @param registerip the value for UserInfo.RegisterIp
     * @mbg.generated Mon Feb 20 11:11:38 CST 2017
     */
    public void setRegisterip(String registerip) {
        this.registerip = registerip == null ? null : registerip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UserInfo.LoginTime
     *
     * @return the value of UserInfo.LoginTime
     * @mbg.generated Mon Feb 20 11:11:38 CST 2017
     */
    public Date getLogintime() {
        return logintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UserInfo.LoginTime
     *
     * @param logintime the value for UserInfo.LoginTime
     * @mbg.generated Mon Feb 20 11:11:38 CST 2017
     */
    public void setLogintime(Date logintime) {
        this.logintime = logintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UserInfo.Remark
     *
     * @return the value of UserInfo.Remark
     * @mbg.generated Mon Feb 20 11:11:38 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UserInfo.Remark
     *
     * @param remark the value for UserInfo.Remark
     * @mbg.generated Mon Feb 20 11:11:38 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UserInfo.DataSource
     *
     * @return the value of UserInfo.DataSource
     * @mbg.generated Mon Feb 20 11:11:38 CST 2017
     */
    public String getDatasource() {
        return datasource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UserInfo.DataSource
     *
     * @param datasource the value for UserInfo.DataSource
     * @mbg.generated Mon Feb 20 11:11:38 CST 2017
     */
    public void setDatasource(String datasource) {
        this.datasource = datasource == null ? null : datasource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UserInfo.HeadImage
     *
     * @return the value of UserInfo.HeadImage
     * @mbg.generated Mon Feb 20 11:11:38 CST 2017
     */
    public String getHeadimage() {
        return headimage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UserInfo.HeadImage
     *
     * @param headimage the value for UserInfo.HeadImage
     * @mbg.generated Mon Feb 20 11:11:38 CST 2017
     */
    public void setHeadimage(String headimage) {
        this.headimage = headimage == null ? null : headimage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UserInfo.CityCode
     *
     * @return the value of UserInfo.CityCode
     * @mbg.generated Mon Feb 20 11:11:38 CST 2017
     */
    public String getCitycode() {
        return citycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UserInfo.CityCode
     *
     * @param citycode the value for UserInfo.CityCode
     * @mbg.generated Mon Feb 20 11:11:38 CST 2017
     */
    public void setCitycode(String citycode) {
        this.citycode = citycode == null ? null : citycode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column UserInfo.WxOpenId
     *
     * @return the value of UserInfo.WxOpenId
     * @mbg.generated Mon Feb 20 11:11:38 CST 2017
     */
    public String getWxopenid() {
        return wxopenid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column UserInfo.WxOpenId
     *
     * @param wxopenid the value for UserInfo.WxOpenId
     * @mbg.generated Mon Feb 20 11:11:38 CST 2017
     */
    public void setWxopenid(String wxopenid) {
        this.wxopenid = wxopenid == null ? null : wxopenid.trim();
    }


    //扩展字段
    /**
     * 城市
     */
    private City city;


    public City getCity() {
        return city;
    }

    public void setCity(City city) {
        this.city = city;
    }


    /**
     * 交易数量
     */
    private int orderCount;
    /**
     * 交易金额
     */
    private double orderAmount;

    public int getOrderCount() {
        return orderCount;
    }

    public void setOrderCount(int orderCount) {
        this.orderCount = orderCount;
    }

    public double getOrderAmount() {
        return orderAmount;
    }

    public void setOrderAmount(double orderAmount) {
        this.orderAmount = orderAmount;
    }

}